use_frameworks!

platform :ios, '8.0'

target 'UCAppDelegateReduce_Example' do
  pod 'UCAppDelegateReduce', :path => '../'

  target 'UCAppDelegateReduce_Tests' do
    inherit! :search_paths
  end
end
